-- Generated by scripts/generate-ai-case-catalog-sql.mjs.
-- The canonical source is data/ai-public-cases.json.

create table if not exists public.ai_knowledge_clients (
  id uuid primary key default gen_random_uuid(),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  slug text not null unique,
  name text not null,
  aliases jsonb not null default '[]'::jsonb,
  published boolean not null default true
);

create table if not exists public.ai_knowledge_cases (
  id uuid primary key default gen_random_uuid(),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  slug text not null unique,
  client_id uuid references public.ai_knowledge_clients(id) on delete set null,
  display_name text not null,
  vertical text not null,
  category text not null,
  title text not null,
  summary text not null,
  task text not null,
  solution text not null,
  result text not null,
  tags jsonb not null default '[]'::jsonb,
  public_url text not null,
  sort_order integer not null default 0,
  published boolean not null default true
);

create table if not exists public.ai_knowledge_case_aliases (
  case_id uuid not null references public.ai_knowledge_cases(id) on delete cascade,
  alias text not null,
  normalized_alias text not null,
  primary key (case_id, normalized_alias)
);

create table if not exists public.ai_knowledge_claims (
  id uuid primary key default gen_random_uuid(),
  case_id uuid not null references public.ai_knowledge_cases(id) on delete cascade,
  kind text not null check (kind in ('summary', 'task', 'solution', 'result')),
  content text not null,
  source_url text not null,
  published boolean not null default true,
  unique (case_id, kind)
);

create table if not exists public.ai_knowledge_assets (
  id uuid primary key default gen_random_uuid(),
  case_id uuid not null references public.ai_knowledge_cases(id) on delete cascade,
  kind text not null check (kind in ('case_page', 'image', 'video', 'document')),
  label text not null,
  url text not null,
  published boolean not null default true,
  verified_at timestamptz not null default now(),
  unique (case_id, kind, url)
);

create index if not exists ai_knowledge_cases_vertical_idx
  on public.ai_knowledge_cases(vertical, published, sort_order);
create index if not exists ai_knowledge_aliases_normalized_idx
  on public.ai_knowledge_case_aliases(normalized_alias);

alter table public.ai_knowledge_clients enable row level security;
alter table public.ai_knowledge_cases enable row level security;
alter table public.ai_knowledge_case_aliases enable row level security;
alter table public.ai_knowledge_claims enable row level security;
alter table public.ai_knowledge_assets enable row level security;

revoke all on table public.ai_knowledge_clients from anon, authenticated;
revoke all on table public.ai_knowledge_cases from anon, authenticated;
revoke all on table public.ai_knowledge_case_aliases from anon, authenticated;
revoke all on table public.ai_knowledge_claims from anon, authenticated;
revoke all on table public.ai_knowledge_assets from anon, authenticated;
grant all on table public.ai_knowledge_clients to service_role;
grant all on table public.ai_knowledge_cases to service_role;
grant all on table public.ai_knowledge_case_aliases to service_role;
grant all on table public.ai_knowledge_claims to service_role;
grant all on table public.ai_knowledge_assets to service_role;

create or replace function public.ai_normalize_search_text(value text)
returns text
language sql
immutable
parallel safe
as $$
  select trim(regexp_replace(replace(lower(coalesce(value, '')), 'ё', 'е'), '[^a-zа-я0-9]+', ' ', 'g'));
$$;

with input(slug, name, aliases, published) as (values
  ('clappy', 'Clappy', '["Клаппи"]'::jsonb, true),
  ('hemotech-ai', 'Hemotech AI', '["Гемотех","Хемотех","Hemotech"]'::jsonb, true),
  ('tpes', 'ТПЭС', '["TPES"]'::jsonb, true),
  ('mfti-endowment', 'Эндаумент-фонд МФТИ', '["Физтех","МФТИ","MIPT Endowment"]'::jsonb, true),
  ('mosfarma', 'Мосфарма', '["MosPharma","МосФарма"]'::jsonb, true),
  ('multon-partners', 'Мултон Партнерс', '["Multon Partners","Мултон"]'::jsonb, true),
  ('avineiro', 'Авинейро', '["Avineiro","Авинейро Фарма"]'::jsonb, true),
  ('rchk', 'АНО «Развитие человеческого капитала»', '["РЧК","Развитие человеческого капитала"]'::jsonb, true)
)
insert into public.ai_knowledge_clients (slug, name, aliases, published)
select slug, name, aliases, published from input
on conflict (slug) do update set
  name = excluded.name,
  aliases = excluded.aliases,
  published = excluded.published,
  updated_at = now();

with input(
  slug, client_slug, display_name, vertical, category, title,
  summary, task, solution, result, tags, public_url, sort_order, published
) as (values
  (
    'clappy', 'clappy', 'Clappy',
    'b2b', 'B2B2C explainer', 'Clappy: объясняющий ролик для сложного B2B2C-продукта',
    'До ролика продукт приходилось долго объяснять. Anix собрала короткую историю, где зритель быстрее понимает проблему, решение и пользу продукта.', 'Продукт было сложно быстро объяснить двум аудиториям. Длинное объяснение мешало первому касанию.', 'Собрали короткую визуальную историю, в которой проблема, решение и польза продукта считываются последовательно.', 'По данным кейса Anix, отклик вырос в несколько десятков раз, а компания дошла до первых пилотов.',
    '["explainer","продукт","первые пилоты"]'::jsonb, 'https://studio.anix-ai.pro/cases/clappy/', 10, true
  ),
  (
    'hemotech-ai', 'hemotech-ai', 'Hemotech AI',
    'medicine', 'MedTech / AI-диагностика', 'Hemotech AI: ролик для сложного MedTech-продукта',
    'Спокойный минималистичный ролик о сложном медицинском AI-продукте стал частью визуального языка бренда.', 'Снизить недоверие к инновационному медицинскому продукту и быстро объяснить его врачам, клиникам и участникам конференций без перегруженного AI-пафоса.', 'Создали короткий минималистичный ролик-визитку и чистый визуальный язык, который команда затем использовала в презентационных материалах.', 'По оценке фаундера, охваты и отклик выросли в несколько десятков раз; стиль ролика стал частью бренда, а команда заказала второй ролик.',
    '["medtech","врачи","доверие","AI-диагностика"]'::jsonb, 'https://studio.anix-ai.pro/cases/hemotech-ai/', 20, true
  ),
  (
    'tpes', 'tpes', 'ТПЭС',
    'b2b', 'Промышленный B2B', 'ТПЭС: ролик вместо 50-страничной презентации',
    'Короткий ролик показывает проблему реактивных потерь, решение и ценность технологии для промышленных предприятий.', 'Сложную техническую проблему приходилось объяснять через длинную презентацию, которая не помогала быстро заинтересовать собственников предприятий.', 'Создали яркий анимационный ролик о реактивных потерях, решении и энергоэффективности для первого касания и конференций.', 'По данным кейса Anix, конверсия в отклик выросла на 30%; фаундер стал отправлять ролик вместо визитки.',
    '["промышленность","продажи","конференции","энергоэффективность"]'::jsonb, 'https://studio.anix-ai.pro/cases/tpes/', 30, true
  ),
  (
    'mfti-endowment', 'mfti-endowment', 'Эндаумент-фонд МФТИ',
    'b2b', 'PR и узнаваемость', 'Эндаумент-фонд МФТИ: анимация как PR-инфоповод',
    'Реальные фотографии МФТИ превратились в тёплую анимационную систему и самостоятельный PR-инфоповод.', 'Создать узнаваемый атмосферный материал, который поможет аудитории понять роль фонда и привлечёт новых дарителей.', 'Перевели реальные фотографии университета в тёплый мультяшный стиль и собрали вдохновляющий ролик с единой визуальной системой.', 'По данным кейса Anix, Telegram почти удвоился, посещаемость сайта выросла втрое, а ERV ролика оказался в 10 раз выше обычного контента.',
    '["PR","анимационная система","охваты","МФТИ"]'::jsonb, 'https://studio.anix-ai.pro/cases/mfti-endowment/', 40, true
  ),
  (
    'mosfarma', 'mosfarma', 'Мосфарма',
    'medicine', 'Фарма / ТВ-реклама', 'Мосфарма: анимационный ролик с бренд-персонажами',
    'Anix сохранила узнаваемость существующих персонажей, сделала их живее и теплее и подготовила анимационный ТВ-ролик.', 'Выпустить рекламный ролик для Первого канала, сохранив уже разработанных бренд-персонажей, которые в исходных концептах выглядели холодными и неэмоциональными.', 'Сохранили сходство с исходными героями, сделали их живее, милее и эмоциональнее, а анимацию приблизили к классическому рекламному формату.', 'Ролик был сдан в срок, прошёл требования Первого канала и получился теплее и убедительнее для зрителя.',
    '["фарма","персонажи","ТВ","реклама"]'::jsonb, 'https://studio.anix-ai.pro/cases/mosfarma/', 50, true
  ),
  (
    'multon-partners', 'multon-partners', 'Мултон Партнерс',
    'hse', 'HSE / жизненно важные правила', 'Мултон Партнерс: маскот и визуальная система для HSE',
    'Маскот кампании и визуальный формат карточек стали системой регулярной внутренней коммуникации жизненно важных правил.', 'Привлечь внимание сотрудников к жизненно важным правилам безопасности и уйти от формата разового плаката и формальных инструкций.', 'С нуля разработали яркого персонажа кампании и визуальный формат карточек LSR для регулярной внутренней коммуникации.', 'Компания получила полноценный визуальный инструмент; карточки активно используются, а маскот стал узнаваемым проводником правил безопасности.',
    '["HSE","маскот","LSR","карточки","охрана труда"]'::jsonb, 'https://studio.anix-ai.pro/cases/multon-partners/', 60, true
  ),
  (
    'aviandr', 'avineiro', 'Авиандр',
    'medicine', 'Фарма / медицинская анимация', 'Авиандр: доказательная база, которая работает на доверие',
    'Научно корректный анимационный ролик, Доктор Коала и маскот «А» помогают объяснять сложное и привлекать внимание врачей.', 'Перевести доказательную базу, механизм действия, безопасность и эффективность препарата в понятную визуальную историю для врачебной аудитории.', 'Разработали Доктора Коалу как спокойного проводника, маскот «А», единый визуальный язык и конференционный ролик.', 'Ролик стал заметным инструментом оформления стенда: люди подходили, останавливались, смотрели и обсуждали материал.',
    '["фарма","доказательная база","маскот","конференция","врачи"]'::jsonb, 'https://studio.anix-ai.pro/cases/aviandr/', 70, true
  ),
  (
    'little-prince', null, 'Маленький принц',
    'cinema', 'Cinema / Creative', '«Маленький принц»: художественный ролик за один день',
    'Атмосферный художественный ролик-фантазия, созданный за несколько часов для крупного медиахолдинга под NDA.', 'За несколько часов создать современную визуальную интерпретацию темы «Маленького принца», сохранив поэтичность и эмоциональное узнавание оригинала.', 'Собрали ролик-фантазию с современным визуальным языком и сфокусировались на атмосфере и эмоциональном попадании, а не на буквальной экранизации.', 'Кейс собрал сотни отзывов от режиссёров, продюсеров, руководителей индустриальных центров и представителей медиа.',
    '["creative","AI-video","имиджевый ролик","кино"]'::jsonb, 'https://studio.anix-ai.pro/cases/little-prince/', 80, true
  ),
  (
    'borodino', null, 'Бородино',
    'cinema', 'Cinema / Historical', '«Бородино»: историческая достоверность без постановочной условности',
    'Художественно-документальный ролик о Бородинском сражении с упором на историческую достоверность и визуальный реализм.', 'Совместить кинематографичность с исторической точностью в костюмах, оружии, среде, поведении войск, звуке и деталях военного быта.', 'Провели историческую подготовку, изучили материалы по периоду и визуальные референсы, затем собрали ультрареалистичный ролик.', 'Кейс получил сильные отзывы за реализм и внимание к деталям и стал одним из лучших проектов студии по исторической достоверности.',
    '["история","cinematic","research","реализм"]'::jsonb, 'https://studio.anix-ai.pro/cases/borodino/', 90, true
  ),
  (
    'rchk', 'rchk', 'РЧК',
    'events', 'События / ролики с ИИ', 'РЧК: от выступления до техно шоу',
    'Получасовое выступление, шесть типов материалов и 5,5-минутный ролик с ИИ, реальными героями и восемью цифровыми мирами.', 'Собрать получасовое выступление для большой внутренней аудитории и превзойти высокую планку прошлогоднего интерактива.', 'Anix взяла на себя сценарий и режиссуру блока, главный ролик, интервью, презентации, экранную графику и фоновую анимацию.', 'Главный ролик прошёл тестовые просмотры и получил оценку «очень круто»; требуемый вау-эффект сработал.',
    '["событие","ролик с ИИ","режиссура","кинопроизводство"]'::jsonb, 'https://studio.anix-ai.pro/cases/rchk/', 100, true
  )
)
insert into public.ai_knowledge_cases (
  slug, client_id, display_name, vertical, category, title,
  summary, task, solution, result, tags, public_url, sort_order, published
)
select
  input.slug, client.id, input.display_name, input.vertical, input.category,
  input.title, input.summary, input.task, input.solution, input.result,
  input.tags, input.public_url, input.sort_order, input.published
from input
left join public.ai_knowledge_clients as client on client.slug = input.client_slug
on conflict (slug) do update set
  client_id = excluded.client_id,
  display_name = excluded.display_name,
  vertical = excluded.vertical,
  category = excluded.category,
  title = excluded.title,
  summary = excluded.summary,
  task = excluded.task,
  solution = excluded.solution,
  result = excluded.result,
  tags = excluded.tags,
  public_url = excluded.public_url,
  sort_order = excluded.sort_order,
  published = excluded.published,
  updated_at = now();

with input(case_slug, alias) as (values
  ('clappy', 'Clappy'),
  ('clappy', 'Клаппи'),
  ('hemotech-ai', 'Hemotech AI'),
  ('hemotech-ai', 'Hemotech'),
  ('hemotech-ai', 'Гемотех'),
  ('hemotech-ai', 'Хемотех'),
  ('hemotech-ai', 'Гемотех AI'),
  ('tpes', 'ТПЭС'),
  ('tpes', 'TPES'),
  ('mfti-endowment', 'Эндаумент-фонд МФТИ'),
  ('mfti-endowment', 'Эндаумент МФТИ'),
  ('mfti-endowment', 'Фонд МФТИ'),
  ('mfti-endowment', 'MIPT Endowment'),
  ('mosfarma', 'Мосфарма'),
  ('mosfarma', 'MosPharma'),
  ('multon-partners', 'Мултон Партнерс'),
  ('multon-partners', 'Мултон'),
  ('multon-partners', 'Multon Partners'),
  ('multon-partners', 'Multon'),
  ('aviandr', 'Авиандр'),
  ('aviandr', 'Aviandr'),
  ('aviandr', 'Авинейро'),
  ('aviandr', 'Доктор Коала'),
  ('little-prince', 'Маленький принц'),
  ('little-prince', 'The Little Prince'),
  ('little-prince', 'Little Prince'),
  ('borodino', 'Бородино'),
  ('borodino', 'Бородинское сражение'),
  ('borodino', 'Borodino'),
  ('rchk', 'РЧК'),
  ('rchk', 'АНО РЧК'),
  ('rchk', 'Развитие человеческого капитала'),
  ('rchk', 'техно шоу')
)
insert into public.ai_knowledge_case_aliases (case_id, alias, normalized_alias)
select case_record.id, input.alias, public.ai_normalize_search_text(input.alias)
from input
join public.ai_knowledge_cases as case_record on case_record.slug = input.case_slug
on conflict (case_id, normalized_alias) do update set alias = excluded.alias;

with input(case_slug, kind, content, source_url, published) as (values
  ('clappy', 'summary', 'До ролика продукт приходилось долго объяснять. Anix собрала короткую историю, где зритель быстрее понимает проблему, решение и пользу продукта.', 'https://studio.anix-ai.pro/cases/clappy/', true),
  ('clappy', 'task', 'Продукт было сложно быстро объяснить двум аудиториям. Длинное объяснение мешало первому касанию.', 'https://studio.anix-ai.pro/cases/clappy/', true),
  ('clappy', 'solution', 'Собрали короткую визуальную историю, в которой проблема, решение и польза продукта считываются последовательно.', 'https://studio.anix-ai.pro/cases/clappy/', true),
  ('clappy', 'result', 'По данным кейса Anix, отклик вырос в несколько десятков раз, а компания дошла до первых пилотов.', 'https://studio.anix-ai.pro/cases/clappy/', true),
  ('hemotech-ai', 'summary', 'Спокойный минималистичный ролик о сложном медицинском AI-продукте стал частью визуального языка бренда.', 'https://studio.anix-ai.pro/cases/hemotech-ai/', true),
  ('hemotech-ai', 'task', 'Снизить недоверие к инновационному медицинскому продукту и быстро объяснить его врачам, клиникам и участникам конференций без перегруженного AI-пафоса.', 'https://studio.anix-ai.pro/cases/hemotech-ai/', true),
  ('hemotech-ai', 'solution', 'Создали короткий минималистичный ролик-визитку и чистый визуальный язык, который команда затем использовала в презентационных материалах.', 'https://studio.anix-ai.pro/cases/hemotech-ai/', true),
  ('hemotech-ai', 'result', 'По оценке фаундера, охваты и отклик выросли в несколько десятков раз; стиль ролика стал частью бренда, а команда заказала второй ролик.', 'https://studio.anix-ai.pro/cases/hemotech-ai/', true),
  ('tpes', 'summary', 'Короткий ролик показывает проблему реактивных потерь, решение и ценность технологии для промышленных предприятий.', 'https://studio.anix-ai.pro/cases/tpes/', true),
  ('tpes', 'task', 'Сложную техническую проблему приходилось объяснять через длинную презентацию, которая не помогала быстро заинтересовать собственников предприятий.', 'https://studio.anix-ai.pro/cases/tpes/', true),
  ('tpes', 'solution', 'Создали яркий анимационный ролик о реактивных потерях, решении и энергоэффективности для первого касания и конференций.', 'https://studio.anix-ai.pro/cases/tpes/', true),
  ('tpes', 'result', 'По данным кейса Anix, конверсия в отклик выросла на 30%; фаундер стал отправлять ролик вместо визитки.', 'https://studio.anix-ai.pro/cases/tpes/', true),
  ('mfti-endowment', 'summary', 'Реальные фотографии МФТИ превратились в тёплую анимационную систему и самостоятельный PR-инфоповод.', 'https://studio.anix-ai.pro/cases/mfti-endowment/', true),
  ('mfti-endowment', 'task', 'Создать узнаваемый атмосферный материал, который поможет аудитории понять роль фонда и привлечёт новых дарителей.', 'https://studio.anix-ai.pro/cases/mfti-endowment/', true),
  ('mfti-endowment', 'solution', 'Перевели реальные фотографии университета в тёплый мультяшный стиль и собрали вдохновляющий ролик с единой визуальной системой.', 'https://studio.anix-ai.pro/cases/mfti-endowment/', true),
  ('mfti-endowment', 'result', 'По данным кейса Anix, Telegram почти удвоился, посещаемость сайта выросла втрое, а ERV ролика оказался в 10 раз выше обычного контента.', 'https://studio.anix-ai.pro/cases/mfti-endowment/', true),
  ('mosfarma', 'summary', 'Anix сохранила узнаваемость существующих персонажей, сделала их живее и теплее и подготовила анимационный ТВ-ролик.', 'https://studio.anix-ai.pro/cases/mosfarma/', true),
  ('mosfarma', 'task', 'Выпустить рекламный ролик для Первого канала, сохранив уже разработанных бренд-персонажей, которые в исходных концептах выглядели холодными и неэмоциональными.', 'https://studio.anix-ai.pro/cases/mosfarma/', true),
  ('mosfarma', 'solution', 'Сохранили сходство с исходными героями, сделали их живее, милее и эмоциональнее, а анимацию приблизили к классическому рекламному формату.', 'https://studio.anix-ai.pro/cases/mosfarma/', true),
  ('mosfarma', 'result', 'Ролик был сдан в срок, прошёл требования Первого канала и получился теплее и убедительнее для зрителя.', 'https://studio.anix-ai.pro/cases/mosfarma/', true),
  ('multon-partners', 'summary', 'Маскот кампании и визуальный формат карточек стали системой регулярной внутренней коммуникации жизненно важных правил.', 'https://studio.anix-ai.pro/cases/multon-partners/', true),
  ('multon-partners', 'task', 'Привлечь внимание сотрудников к жизненно важным правилам безопасности и уйти от формата разового плаката и формальных инструкций.', 'https://studio.anix-ai.pro/cases/multon-partners/', true),
  ('multon-partners', 'solution', 'С нуля разработали яркого персонажа кампании и визуальный формат карточек LSR для регулярной внутренней коммуникации.', 'https://studio.anix-ai.pro/cases/multon-partners/', true),
  ('multon-partners', 'result', 'Компания получила полноценный визуальный инструмент; карточки активно используются, а маскот стал узнаваемым проводником правил безопасности.', 'https://studio.anix-ai.pro/cases/multon-partners/', true),
  ('aviandr', 'summary', 'Научно корректный анимационный ролик, Доктор Коала и маскот «А» помогают объяснять сложное и привлекать внимание врачей.', 'https://studio.anix-ai.pro/cases/aviandr/', true),
  ('aviandr', 'task', 'Перевести доказательную базу, механизм действия, безопасность и эффективность препарата в понятную визуальную историю для врачебной аудитории.', 'https://studio.anix-ai.pro/cases/aviandr/', true),
  ('aviandr', 'solution', 'Разработали Доктора Коалу как спокойного проводника, маскот «А», единый визуальный язык и конференционный ролик.', 'https://studio.anix-ai.pro/cases/aviandr/', true),
  ('aviandr', 'result', 'Ролик стал заметным инструментом оформления стенда: люди подходили, останавливались, смотрели и обсуждали материал.', 'https://studio.anix-ai.pro/cases/aviandr/', true),
  ('little-prince', 'summary', 'Атмосферный художественный ролик-фантазия, созданный за несколько часов для крупного медиахолдинга под NDA.', 'https://studio.anix-ai.pro/cases/little-prince/', true),
  ('little-prince', 'task', 'За несколько часов создать современную визуальную интерпретацию темы «Маленького принца», сохранив поэтичность и эмоциональное узнавание оригинала.', 'https://studio.anix-ai.pro/cases/little-prince/', true),
  ('little-prince', 'solution', 'Собрали ролик-фантазию с современным визуальным языком и сфокусировались на атмосфере и эмоциональном попадании, а не на буквальной экранизации.', 'https://studio.anix-ai.pro/cases/little-prince/', true),
  ('little-prince', 'result', 'Кейс собрал сотни отзывов от режиссёров, продюсеров, руководителей индустриальных центров и представителей медиа.', 'https://studio.anix-ai.pro/cases/little-prince/', true),
  ('borodino', 'summary', 'Художественно-документальный ролик о Бородинском сражении с упором на историческую достоверность и визуальный реализм.', 'https://studio.anix-ai.pro/cases/borodino/', true),
  ('borodino', 'task', 'Совместить кинематографичность с исторической точностью в костюмах, оружии, среде, поведении войск, звуке и деталях военного быта.', 'https://studio.anix-ai.pro/cases/borodino/', true),
  ('borodino', 'solution', 'Провели историческую подготовку, изучили материалы по периоду и визуальные референсы, затем собрали ультрареалистичный ролик.', 'https://studio.anix-ai.pro/cases/borodino/', true),
  ('borodino', 'result', 'Кейс получил сильные отзывы за реализм и внимание к деталям и стал одним из лучших проектов студии по исторической достоверности.', 'https://studio.anix-ai.pro/cases/borodino/', true),
  ('rchk', 'summary', 'Получасовое выступление, шесть типов материалов и 5,5-минутный ролик с ИИ, реальными героями и восемью цифровыми мирами.', 'https://studio.anix-ai.pro/cases/rchk/', true),
  ('rchk', 'task', 'Собрать получасовое выступление для большой внутренней аудитории и превзойти высокую планку прошлогоднего интерактива.', 'https://studio.anix-ai.pro/cases/rchk/', true),
  ('rchk', 'solution', 'Anix взяла на себя сценарий и режиссуру блока, главный ролик, интервью, презентации, экранную графику и фоновую анимацию.', 'https://studio.anix-ai.pro/cases/rchk/', true),
  ('rchk', 'result', 'Главный ролик прошёл тестовые просмотры и получил оценку «очень круто»; требуемый вау-эффект сработал.', 'https://studio.anix-ai.pro/cases/rchk/', true)
)
insert into public.ai_knowledge_claims (case_id, kind, content, source_url, published)
select case_record.id, input.kind, input.content, input.source_url, input.published
from input
join public.ai_knowledge_cases as case_record on case_record.slug = input.case_slug
on conflict (case_id, kind) do update set
  content = excluded.content,
  source_url = excluded.source_url,
  published = excluded.published;

with input(case_slug, kind, label, url, published) as (values
  ('clappy', 'case_page', 'Открыть кейс', 'https://studio.anix-ai.pro/cases/clappy/', true),
  ('clappy', 'image', 'Изображение кейса', 'https://studio.anix-ai.pro/seo-media/cases/clappy.webp', true),
  ('clappy', 'video', 'Смотреть видео', 'https://drive.google.com/file/d/1EYWBYlhSgIK4Wd4F0nTKR1kQxYhXGc5j/view', true),
  ('hemotech-ai', 'case_page', 'Открыть кейс', 'https://studio.anix-ai.pro/cases/hemotech-ai/', true),
  ('hemotech-ai', 'image', 'Изображение кейса', 'https://studio.anix-ai.pro/seo-media/cases/hemotech-ai.webp', true),
  ('hemotech-ai', 'video', 'Смотреть видео', 'https://drive.google.com/file/d/1Q6RQlNbAKBGugpo-MH1-_6omwwnmPQ8E/view', true),
  ('tpes', 'case_page', 'Открыть кейс', 'https://studio.anix-ai.pro/cases/tpes/', true),
  ('tpes', 'image', 'Изображение кейса', 'https://studio.anix-ai.pro/seo-media/cases/tpes.webp', true),
  ('tpes', 'video', 'Смотреть видео', 'https://drive.google.com/file/d/1BgJs_mKyvEVtDlWeaXGY9rmFjPKrTes5/view', true),
  ('mfti-endowment', 'case_page', 'Открыть кейс', 'https://studio.anix-ai.pro/cases/mfti-endowment/', true),
  ('mfti-endowment', 'image', 'Изображение кейса', 'https://studio.anix-ai.pro/seo-media/cases/mfti-endowment.webp', true),
  ('mosfarma', 'case_page', 'Открыть кейс', 'https://studio.anix-ai.pro/cases/mosfarma/', true),
  ('mosfarma', 'image', 'Изображение кейса', 'https://studio.anix-ai.pro/seo-media/cases/mosfarma.webp', true),
  ('mosfarma', 'video', 'Смотреть видео', 'https://drive.google.com/file/d/1Uw9e-ZFzg9AVK8NnoN_EHwfR0ZPvD_M0/view', true),
  ('multon-partners', 'case_page', 'Открыть кейс', 'https://studio.anix-ai.pro/cases/multon-partners/', true),
  ('multon-partners', 'image', 'Изображение кейса', 'https://studio.anix-ai.pro/seo-media/cases/multon-partners.webp', true),
  ('aviandr', 'case_page', 'Открыть кейс', 'https://studio.anix-ai.pro/cases/aviandr/', true),
  ('aviandr', 'image', 'Изображение кейса', 'https://studio.anix-ai.pro/seo-media/cases/aviandr-cover.webp', true),
  ('aviandr', 'video', 'Смотреть видео', 'https://vkvideo.ru/video-174933827_456239053', true),
  ('little-prince', 'case_page', 'Открыть кейс', 'https://studio.anix-ai.pro/cases/little-prince/', true),
  ('little-prince', 'image', 'Изображение кейса', 'https://studio.anix-ai.pro/seo-media/cases/little-prince.webp', true),
  ('little-prince', 'video', 'Смотреть видео', 'https://drive.google.com/file/d/1xIOgHxhhloGtBRtrnwp3xpV9AkShUNqT/view', true),
  ('borodino', 'case_page', 'Открыть кейс', 'https://studio.anix-ai.pro/cases/borodino/', true),
  ('borodino', 'image', 'Изображение кейса', 'https://studio.anix-ai.pro/seo-media/cases/borodino.webp', true),
  ('borodino', 'video', 'Смотреть видео', 'https://drive.google.com/file/d/1d2iXB33lqPgG3Y0M4e216nzw2QYGmssP/view', true),
  ('rchk', 'case_page', 'Открыть кейс', 'https://studio.anix-ai.pro/cases/rchk/', true),
  ('rchk', 'image', 'Изображение кейса', 'https://studio.anix-ai.pro/og/home.jpg', true)
)
insert into public.ai_knowledge_assets (case_id, kind, label, url, published)
select case_record.id, input.kind, input.label, input.url, input.published
from input
join public.ai_knowledge_cases as case_record on case_record.slug = input.case_slug
on conflict (case_id, kind, url) do update set
  label = excluded.label,
  published = excluded.published,
  verified_at = now();

create or replace function public.search_ai_public_cases(
  query_text text default '',
  filter_vertical text default null,
  match_count integer default 10
)
returns table (
  id uuid,
  slug text,
  display_name text,
  client_name text,
  vertical text,
  category text,
  title text,
  summary text,
  task text,
  solution text,
  result text,
  tags jsonb,
  public_url text,
  assets jsonb,
  exact_match boolean,
  retrieval_score double precision
)
language sql
stable
security definer
set search_path = public
as $$
  with query as (
    select public.ai_normalize_search_text(query_text) as normalized
  ), ranked as (
    select
      case_record.*,
      client.name as client_name,
      coalesce(max(
        case when query.normalized <> '' and position(
          ' ' || alias.normalized_alias || ' ' in ' ' || query.normalized || ' '
        ) > 0 then 1 else 0 end
      ), 0) = 1 as exact_match,
      coalesce(max(
        case when query.normalized <> '' and position(
          ' ' || alias.normalized_alias || ' ' in ' ' || query.normalized || ' '
        ) > 0 then 100.0 else 0.0 end
      ), 0.0) +
      ts_rank_cd(
        to_tsvector('simple', concat_ws(' ', case_record.display_name, case_record.title, case_record.summary, case_record.tags::text)),
        plainto_tsquery('simple', query.normalized),
        32
      ) * 10.0 as retrieval_score
    from public.ai_knowledge_cases as case_record
    cross join query
    left join public.ai_knowledge_clients as client on client.id = case_record.client_id
    left join public.ai_knowledge_case_aliases as alias on alias.case_id = case_record.id
    where case_record.published = true
      and (filter_vertical is null or case_record.vertical = filter_vertical)
    group by case_record.id, client.name, query.normalized
  )
  select
    ranked.id,
    ranked.slug,
    ranked.display_name,
    ranked.client_name,
    ranked.vertical,
    ranked.category,
    ranked.title,
    ranked.summary,
    ranked.task,
    ranked.solution,
    ranked.result,
    ranked.tags,
    ranked.public_url,
    coalesce((
      select jsonb_agg(jsonb_build_object(
        'id', asset.id,
        'kind', asset.kind,
        'label', asset.label,
        'url', asset.url
      ) order by case asset.kind when 'case_page' then 1 when 'video' then 2 else 3 end)
      from public.ai_knowledge_assets as asset
      where asset.case_id = ranked.id and asset.published = true
    ), '[]'::jsonb) as assets,
    ranked.exact_match,
    ranked.retrieval_score
  from ranked
  where public.ai_normalize_search_text(query_text) = ''
    or ranked.exact_match
    or ranked.retrieval_score > 0.01
  order by ranked.exact_match desc, ranked.retrieval_score desc, ranked.sort_order
  limit greatest(1, least(match_count, 30));
$$;

revoke all on function public.search_ai_public_cases(text, text, integer)
  from public, anon, authenticated;
grant execute on function public.search_ai_public_cases(text, text, integer)
  to service_role;
