name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]      # собираем каждый раз, когда пуш в main
  workflow_dispatch:        # можно запустить вручную в закладке Actions

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Use Node
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install deps
        run: npm ci

      - name: Build
        run: npm run build

      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build         # та же папка, что в npm run build
          publish_branch: gh-pages
