name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Use Node
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Cache node modules
        uses: actions/cache@v4
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install deps
        id: npm-install
        run: npm install

      - name: Notify if install failed
        if: steps.npm-install.outcome == 'failure'
        run: echo "npm install failed"

      - name: Build
        if: steps.npm-install.outcome == 'success'
        run: npm run build

      - name: Prepare 404 page
        if: steps.npm-install.outcome == 'success'
        run: cp build/index.html build/404.html

      - name: Deploy to gh-pages
        if: steps.npm-install.outcome == 'success'
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build
          publish_branch: gh-pages
          cname: studio.anix-ai.pro
