name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Use Node
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install deps
        id: npm-ci
        run: npm ci
        continue-on-error: true

      - name: Notify if install failed
        if: steps.npm-ci.outcome == 'failure'
        run: echo "npm ci failed. Run 'npm install' locally and commit the updated lockfile."

      - name: Build
        if: steps.npm-ci.outcome == 'success'
        run: npm run build

      - name: Prepare 404 page
        if: steps.npm-ci.outcome == 'success'
        run: cp build/index.html build/404.html
        
      - name: Add CNAME file
        run: echo "studio.anix-ai.pro" > build/CNAME

      - name: Deploy to gh-pages
        if: steps.npm-ci.outcome == 'success'
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build
          publish_branch: gh-pages
